# 본문의 글은 인프런 앨런 Swift문법 마스터 스쿨(온라인) 부트캠프의 강의 영상을 본후 공부한 내용을 정리하여 기록한것입니다.
https://inf.run/YyoR


```swift
//Never 타입과 검증함수 (실무와 관련)

//Never 타입
/*
 함수의 리턴의 의미
 함수의 리턴은 값의리턴, 제어권리턴(함수끝내는거)
 */

func addTwoNumbers(a: Int, b: Int) -> Int { //90
    let c = a + b                           //91
    return c                                //92 ->값을가지고 1003번으로 돌아감 //Cpu실행의 제어권도 돌려줌
}


//main()함수 영역이라고 가정

var num1 = 5                                 //1000
var num2 = 3                                 //1001

var num3 = addTwoNumbers(a: num1, b: num2)   //1002 -> 90번으로 가서 함수 실행.
print(num3)                                  //1003


//이런 값을 리턴한다는건 함수 내부로 전달했던 CPU실행의 제어권을 다시 돌려준다는 의미기도  하다.
//Never은 이런 제어권을 절대 돌려주지않겠다 라는 의미이다.

//Never타입과 함수의 제어권을 Nonreturning 하는 함수들 ======================

//리턴형인 Never타입인 함수의 이해

func crashAndBurn() -> Never { //리턴을 쓰는곳에 Never를 쓰면됨
    fatalError("앱의 해킹이 발견") //여기서 원래 함수 실행위치로 돌아가지않음 제어권을 안돌려줌
} //fatalError 라는 녀석은 내부에 Never타입을 가지고 있음.


print("1")
//crashAndBurn()
print("2") //위에 코멘트를 제거해보면 절대 실행되않는다고 뜬다


/*
 Nonreturning 함수
 제어권을 반환하지 않는 함수
 
 명시적으로 제어권을 전달하지 않는다는 것을 표시하기 위해 Never 타입으로 선언
 
 Never타입을 리턴하는 함수
 1. 함수내부에서 프로그램을 종료시켜야함 (예: fatalError() )
 2. 항상 에러를 던져서, catch문에서 처리하도록 해야함(제어권을 catch문으로)
 
 
 
 
 Never 타입 (임시적인 타입)
 
 내부가 빈 열거형으로 선언
 인스턴스를 생성할수 없음 (단순 표시 난 이런녀석이야~ 하는 그런 타입이라고 봐야함)
 
 
 애플아 그래서 이건 왜 써!?
 
 런타임(앱실행) 중에 발생할 수 있는 에러를 미리 발견하고 검증/테스트 하기 위함
 
 앱의 해킹이라는 극단적인 예를 들었지만, 실제로 앱의 해킹이 아닌 조금 가벼운 에러라면
 실제 앱을 출시할때는 해당 코드를 삭제해야함
 (삭제하지 않으면 앱이 꺼질 가능성이 높기때문에 사용자편의성이 안좋은 앱으로 평가받음)
 
 
 assert 함수, precondition함수, fatalError함수
 */



//에러를 던지는 Never 타입 함수의 예시 =========================
//어거지로 만든 함수
//실제로는 에러를 던지는게아니라 강제로 앱을 꺼버림


//1. 에러정의
enum SomeError: Error {
    case aError
}


//2. 에러를 던지는 함수를 정의
func someThrowingErrorFunction() throws -> Never {
    if true {
        throw SomeError.aError
    } else {
        throw SomeError.aError
    }
}

//3. 에러를 던지는 함수의 실행

do {
    try someThrowingErrorFunction()
} catch {
    print(error.localizedDescription)
}




//fatal Error() =================================

func someCloseAppsituation() {
    fatalError("앱 해킹시도 발견")
}

//someCloseAppsituation()


/*
 애플 내부에도 많은 함수들이 fatalError로 구현된 경우가 많음

 빨간 줄을 표시하고, 어떤 치명적 에러가 발생했는지도 알려줌 => 실은 개발자에게 체크하고 수정하라고 알려주는것
 
 그럼 우리도 직접 내부에서 동작하는 것처럼
 필요한 경우에 조건에따라서 앱을 종료시키는 에러를 직접 만들수가 있음

 */


//디버깅 함수 =================================
/*
 assert()
 precondition()
 fatalError()
 
 assertionFailure()
 preconditionFailure()
 
 앱을 테스트하여서, 런타임동안 발생할 수 있는 여러 버그의 가능성,
 잘못된코드의 검증 등을 수행하도록 도와 주는 함수
 
 print / dump 이녀석들도 일종의 디버깅 함수다
 어떤 코드들이 입력되는지 콘솔창을 통해 확인/검증이 가능하기때문
 
 
 참고로 fatalError는 저들 중에서 제일 강력한 녀석이다. 웬만한 상황에서는 사용안함

 */






// assert() 출시 이전앱의 검증함수 디버그모드 (왠만하면 여기서 발경해야함) =========================================
//출시모드로 앱스토어에 올리면 실제 출시하는앱에서는 이 함수들이 작동하지않음 디버그모드에서만 작동

//예상하는 범위를 벗어난 결과이지만, 아주 유의미하지는 않아서, 굳이 종료시키는것은 안좋음
//예) 레이블에 20% / 50% / 100% 를 표시한다고 했을때 -10%라고 표시된다면 굳이 앱을 종료해야하는가?

func enterWrongValue1() {
    let someWrongInput = -1
    assert(someWrongInput > 0, "유저가 값을 잘못 입력")
} //someWrongInput이 항상 0보다 커야 동작할수 있다 이런뜻
 //참이되면 함수를 계속 실행, 거짓이면 에러메세지를 출력


//enterWrongValue1()


//assertionFailure은 형제같은녀석인데 항상 거짓의 경우에 사용하는 녀석 조건이 거짓이라는걸 가정하고 실행되는것
func enterWorngValue2() {
    let someWrongInput = -1
    
    if someWrongInput > 0 {
        print("정상적으로 동작하는 코드는 여기에")
    } else {
        assertionFailure("유저가 잘못된 값을 입력했음")
    }
}


//enterWorngValue2()



// precondition() 출시버전앱의 검증함수 출시모드 ========================================
//조금 더 심각한상황에서 쓰는 검증함수 출시하는앱에서도 종료를 시킴 = 유저한테 불편을 주더라도...

//유의미하기때문에 앱을일부러 종료해야함
//예) 앱의 업데이트로 인해 버전이 업데이트 되었는데 이전 버전을 계속 깔고 있다면
// 서버와의 통신이 잘못될수도 있기때문에 종료시켜야 할수도 있음
//assert와 형식,사용법은 완전 동일


func appUpdateCheck1() {
    let update = false
    precondition(update, "앱을 업데이트 하지 않음")
}


//appUpdateCheck1()




func appUpdateCheck2() {
    let update = false
    
    if update {
        // 앱을 업데이트 했을때, 정상적으로 실행할 코드
        
    } else {
        preconditionFailure("앱을 업데이트 하지 않음")
    }
}


//appUpdateCheck2()


/*
 컴파일오류 = 플레이그라운드에서 자주 뜨는그 빨간거
 코드가 잘못되었음을 알려줌 (문법적으로 잘못된거)
 
 런타임오류의 3가지
  에러처리: 프로그래머가 제어 불가능한 영역이지만 미리 정의해놓으면 얼럿창 등을 띄우는것이 가능
 여러가지 다양한 이유로 앱이 실행되는 동안 발생 => 앱이 꺼짐
 미리 발생가능한 에러를 파악, 올바르게 처리하면 앱의 꺼짐을 막을 수 있음
 
 예) 서버다운/ 업데이트 안함 = 얼럿띄우고 종료
 
 
 프로그래머의 실수
 assert(): 검증함수를 통한 개선
 디버그 모드에서 검증 (출시모드에서 조치 안함)
 검증코드를 곳곳에 넣어놓고 확인
 예) 마이너스가 입력될수없다고 생각한곳에 마이너스값을 입력함
 
 유저로인한 외부적인 요인
 preconditon() : 검증함수를 통해확인
 디버그모드에서 검증, 또한 출시모드에서도 검증함
 검증코드를 곳곳에 넣어놓고 확인
 예) 업데이트안함, 앱을 이상하게 조작: 앱꺼짐
 
 */
```